version: "3"
services:
  db:
    image: mongo
    container_name: smkt-mongo
    restart: always
    volumes:
      - /opt/smkt/mongoData:/data/db
    networks:
      smkt:
        ipv4_address: 172.0.0.2
  mysqlDB:
    image: mysql:latest
    container_name: smkt-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'SMKT_USERS'
      MYSQL_USER: 'smkt'
      MYSQL_PASSWORD: 'Smkt@123'
      MYSQL_ROOT_PASSWORD: 'password'
    networks: 
      smkt:
        ipv4_address: 172.0.0.20
  eureka:
    image: antonioalejandro01/smkt-eureka:1
    container_name: smkt-eureka
    expose:
      - "8761"
    ports: 
      - "8761:8761"
    networks:
      smkt:
        ipv4_address: 172.0.0.3
  gateway:
    image: antonioalejandro01/smkt-gateway:1
    container_name: smkt-gateway
    depends_on:
      - eureka
    expose:
      - "8090"
    ports: 
      - "8090:8090"
    networks:
      smkt:
        ipv4_address: 172.0.0.4
  files:
    image: antonioalejandro01/smkt-files:1
    container_name: smkt-files
    depends_on:
      - gateway
    expose:
      - "4050"
    networks:
      smkt:
        ipv4_address: 172.0.0.5
  kitchen:
    image: antonioalejandro01/smkt-kitchen:1
    container_name: smkt-kitchen
    environment:
      IP_MONGO: "172.0.0.2"
      NODE_ENV: production
      HOST: "172.0.0.6"
      PORT: "4060"
      EUREKA_HOST: "172.0.0.3"
      EUREKA_PORT: "8761"
      EUREKA: "true"
    depends_on:
      - files
    expose:
      - "4060"
    networks:
      smkt:
        ipv4_address: 172.0.0.6
  auth:
    image: antonioalejandro01/smkt-oauth:1
    container_name: smkt-oauth
    depends_on: 
      - gateway
    expose: 
      - "9100"
    networks: 
      smkt:
        ipv4_address: 172.0.0.7
  users:
    image: antonioalejandro01/smkt-users:1
    container_name: smkt-users
    depends_on: 
      - gateway
      - mysqlDB
    expose: 
      - "4070"
    networks: 
      smkt:
        ipv4_address: 172.0.0.8
networks:
  smkt:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.0/24
