version: "3"
services:
  db:
    image: mongo
    container_name: smkt-mongo
    restart: always
    volumes:
      - /opt/smkt/mongoData:/data/db
    networks:
      smkt:
        ipv4_address: 172.0.0.2
  eureka:
    build:
      context: ./SMKT_Eureka
      dockerfile: Dockerfile
    container_name: smkt-eureka
    expose:
      - "8761"
    ports:
      - "8761:8761"
    networks:
      smkt:
        ipv4_address: 172.0.0.3
  gateway:
    build:
      context: ./SMKT_Gateway
      dockerfile: Dockerfile.compose
    container_name: smkt-gateway
    depends_on:
      - eureka
    expose:
      - "8090"
    ports: 
      - "8090:8090"
    networks:
      smkt:
        ipv4_address: 172.0.0.4
  files:
    build:
      context: ./SMKT_Files
      dockerfile: Dockerfile.compose
    container_name: smkt-files
    depends_on:
      - gateway
    expose:
      - "4050"
    networks:
      smkt:
        ipv4_address: 172.0.0.5
  kitchen:
    build:
      context: ./SMKT_Kitchen
      dockerfile: Dockerfile.compose
    container_name: smkt-kitchen
    environment:
      IP_MONGO: "172.0.0.2"
      NODE_ENV: production
      HOST: "172.0.0.6"
      PORT: "4060"
      EUREKA_HOST: "172.0.0.3"
      EUREKA_PORT: "8761"
      EUREKA: "true"
    depends_on:
      - files
    expose:
      - "4060"
    networks:
      smkt:
        ipv4_address: 172.0.0.6
networks:
  smkt:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.0/24
