version: "3"

services:
    mongoDB:
        image: mongo:5
        container_name: smkt-mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secret
        volumes:
            - mongoDBDataLatest:/data/db
    mysqlDB:
        image: mysql:8
        container_name: smkt-mysql
        restart: always
        environment:
            MYSQL_DATABASE: 'SMKT_USERS'
            MYSQL_USER: 'smkt'
            MYSQL_PASSWORD: 'Smkt@123'
            MYSQL_ROOT_PASSWORD: 'password'
        volumes: 
            - sqlDBDataLatest:/var/lib/mysql
    eureka:
        image: antonioalejandro01/smkt-eureka:latest
        container_name: smkt-eureka
        environment:
            PORT: 8761
    gateway:
        image: antonioalejandro01/smkt-gateway:latest
        container_name: smkt-gateway
        environment:
            PORT: 8090
            EUREKA_URL: http://eureka:8761/eureka
        ports: 
            - "8090:8090"
    files:
        image: antonioalejandro01/smkt-files:latest
        container_name: smkt-files
        environment:
            PORT: 4050
            EUREKA_URL: http://eureka:8761/eureka 
        depends_on:
            - gateway
    auth:
        image: antonioalejandro01/smkt-oauth:latest
        container_name: smkt-oauth
        depends_on: 
            - gateway
        environment:
            PORT: 9100
            EUREKA_URL: http://eureka:8761/eureka
    users:
        image: antonioalejandro01/smkt-users:latest
        container_name: smkt-users
        environment:
            PORT: 4060
            EUREKA_URL: http://eureka:8761/eureka
            DATASOURCE_URL: jdbc:mysql://mysqlDB:3306/SMKT_USERS
            DATASOURCE_USER: smkt
            DATASOURCE_PASSWORD: Smkt@123
    pantry:
        image: antonioalejandro01/smkt-pantry:latest
        container_name: smkt-pantry
        depends_on: 
            - gateway
        environment:
            PORT: 4070
            EUREKA_URL: http://eureka:8761/eureka
            DB_NAME: smkt
            DB_CONNECTION: mongodb://root:secret@mongoDB:27017/
    cookbook:
        image: antonioalejandro01/smkt-cookbook:latest
        container_name: smkt-cookbook
        environment:
            PORT: 4080
            EUREKA_URL: http://eureka:8761/eureka
            DB_NAME: smkt
            DB_COLLECTION: recipes
            DB_CONNECTION: mongodb://root:secret@mongoDB:27017/
volumes:
    sqlDBDataLatest:
    mongoDBDataLatest:
